trigger:
master

pool:
  name: Azure Pipelines

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(9facf577-1995-4354-b480-1c1148e24d64)'
    appType: 'webApp'
    appName: 
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

steps:
task: NuGetToolInstaller@1

task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

task: DotNetCoreCLI@2
  name: 'BuildApp'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'