trigger:
master

pool:
  name: Azure Pipelines

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Free Trial(9facf577-1995-4354-b480-1c1148e24d64)'
    command: 'build'

steps:
task: NuGetToolInstaller@1

task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

task: DotNetCoreCLI@2
  name: 'BuildApp'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'